from schemas import *
candidates = [
    Candidate(
        id=1,
        email="alicesmith@example.com",
        first_name="Alice",
        last_name="Smith",
        field_id=3,
        experience_years=3,
        technical_skills=[13, 14, 16],
        job_type=JobType.full_time,
        likes=[],
        dislikes=[],
    ),
    Candidate(
        id=2,
        email="bobjohnson@example.com",
        first_name="Bob",
        last_name="Johnson",
        field_id=1,
        experience_years=2,
        technical_skills=[1, 4, 5],
        job_type=JobType.part_time,
        likes=[],
        dislikes=[],
    ),
    Candidate(
        id=3,
        email="charliewilliams@example.com",
        first_name="Charlie",
        last_name="Williams",
        field_id=3,
        experience_years=4,
        technical_skills=[13, 14, 16],
        job_type=JobType.full_time,
        likes=[3],
        dislikes=[],
    ),
    Candidate(
        id=4,
        email="davidjones@example.com",
        first_name="David",
        last_name="Jones",
        field_id=2,
        experience_years=5,
        technical_skills=[6, 7, 8],
        job_type=JobType.full_time,
        likes=[4],
        dislikes=[],
    ),
    Candidate(
        id=5,
        email="emmabrown@example.com",
        first_name="Emma",
        last_name="Brown",
        field_id=3,
        experience_years=2,
        technical_skills=[14, 16, 17],
        job_type=JobType.temporary,
        likes=[],
        dislikes=[],
    ),
    Candidate(
        id=6,
        email="frankdavis@example.com",
        first_name="Frank",
        last_name="Davis",
        field_id=1,
        experience_years=0,
        technical_skills=[3, 4, 1],
        job_type=JobType.internship,
        likes=[],
        dislikes=[],
    ),
    Candidate(
        id=7,
        email="gracemiller@example.com",
        first_name="Grace",
        last_name="Miller",
        field_id=2,
        experience_years=4,
        technical_skills=[7, 9, 10],
        job_type=JobType.full_time,
        likes=[],
        dislikes=[],
    ),
    Candidate(
        id=8,
        email="hannahwilson@example.com",
        first_name="Hannah",
        last_name="Wilson",
        field_id=3,
        experience_years=2,
        technical_skills=[13, 16, 14],
        job_type=JobType.full_time,
        likes=[8],
        dislikes=[],
    ),
    Candidate(
        id=9,
        email="ianthompson@example.com",
        first_name="Ian",
        last_name="Thompson",
        field_id=3,
        experience_years=3,
        technical_skills=[14, 16, 17],
        job_type=JobType.part_time,
        likes=[],
        dislikes=[],
    ),
    Candidate(
        id=10,
        email="janeroberts@example.com",
        first_name="Jane",
        last_name="Roberts",
        field_id=1,
        experience_years=2,
        technical_skills=[1, 3, 4],
        job_type=JobType.full_time,
        likes=[],
        dislikes=[],
    )
]


jobs = [
    Job(
        id=1,
        title="Software Developer",
        field_id=3,
        description="Develop and maintain web applications.",
        company_id=1,
        location="New York, NY",
        salary=85000,
        technical_skills=[13, 14, 16],
        experience_years=3,
        job_type=JobType.full_time,
        remote=Remote.hybrid,
        likes=[1],
        dislikes=[],
    ),
    Job(
        id=2,
        title="Marketing Specialist",
        field_id=1,
        description="Plan and execute marketing campaigns.",
        company_id=1,
        location="San Francisco, CA",
        salary=70000,
        technical_skills=[1, 2, 4],
        experience_years=2,
        job_type=JobType.full_time,
        remote=Remote.remote,
        likes=[],
        dislikes=[],
    ),
    Job(
        id=3,
        title="Travel Consultant",
        field_id=2,
        description="Provide travel planning services to clients.",
        company_id=2,
        location="Miami, FL",
        salary=60000,
        technical_skills=[6, 8, 10],
        experience_years=4,
        job_type=JobType.full_time,
        remote=Remote.on_site,
        likes=[],
        dislikes=[],
    ),
    Job(
        id=4,
        title="Full-Stack Developer",
        field_id=3,
        description="Develop full-stack web applications.",
        company_id=1,
        location="Austin, TX",
        salary=95000,
        technical_skills=[13, 14, 17],
        experience_years=5,
        job_type=JobType.full_time,
        remote=Remote.hybrid,
        likes=[],
        dislikes=[],
    ),
    Job(
        id=5,
        title="SEO Specialist",
        field_id=1,
        description="Optimize websites for search engines.",
        company_id=3,
        location="Los Angeles, CA",
        salary=75000,
        technical_skills=[1, 2, 5],
        experience_years=3,
        job_type=JobType.full_time,
        remote=Remote.remote,
        likes=[],
        dislikes=[],
    ),
    Job(
        id=6,
        title="Tour Guide",
        field_id=2,
        description="Guide tourists through various destinations.",
        company_id=2,
        location="Las Vegas, NV",
        salary=50000,
        technical_skills=[7, 8, 9],
        experience_years=6,
        job_type=JobType.part_time,
        remote=Remote.on_site,
        likes=[],
        dislikes=[6],
    ),
    Job(
        id=7,
        title="Backend Developer",
        field_id=3,
        description="Develop backend services and APIs.",
        company_id=3,
        location="Seattle, WA",
        salary=90000,
        technical_skills=[13, 16, 17],
        experience_years=4,
        job_type=JobType.full_time,
        remote=Remote.hybrid,
        likes=[7],
        dislikes=[],
    ),
    Job(
        id=8,
        title="Email Marketing Specialist",
        field_id=1,
        description="Create and manage email marketing campaigns.",
        company_id=2,
        location="Boston, MA",
        salary=65000,
        technical_skills=[4, 2, 3],
        experience_years=3,
        job_type=JobType.full_time,
        remote=Remote.remote,
        likes=[],
        dislikes=[],
    ),
    Job(
        id=9,
        title="Customer Service Manager",
        field_id=1,
        description="Manage customer service operations.",
        company_id=3,
        location="Orlando, FL",
        salary=70000,
        technical_skills=[8, 10, 9],
        experience_years=5,
        job_type=JobType.full_time,
        remote=Remote.on_site,
        likes=[],
        dislikes=[],
    ),
    Job(
        id=10,
        title="Frontend Developer",
        field_id=3,
        description="Develop frontend user interfaces.",
        company_id=1,
        location="Chicago, IL",
        salary=85000,
        technical_skills=[14, 13, 11],
        experience_years=3,
        job_type=JobType.full_time,
        remote=Remote.hybrid,
        likes=[],
        dislikes=[],
    )
]


fields = [
    Field(
        id = 1,
        title = 'Marketing',
    ),
    Field(
        id = 2,
        title = 'Tourism',
    ),
    Field(
        id = 3,
        title = 'Softwawre',
    ),
]

skills = [
    # Marketing Skills
    Skill(id=1, title='SEO', field_id=1),
    Skill(id=2, title='Content Creation', field_id=1),
    Skill(id=3, title='Social Media Management', field_id=1),
    Skill(id=4, title='Email Marketing', field_id=1),
    Skill(id=5, title='PPC Campaigns', field_id=1),
    
    # Tourism Skills
    Skill(id=6, title='Travel Planning', field_id=2),
    Skill(id=7, title='Tour Guiding', field_id=2),
    Skill(id=8, title='Customer Service', field_id=2),
    Skill(id=9, title='Itinerary Design', field_id=2),
    Skill(id=10, title='Booking Management', field_id=2),

    # Software Skills
    Skill(id=11, title='Debugging', field_id=3),
    Skill(id=12, title='Software Design', field_id=3),
    Skill(id=13, title='Node.js', field_id=3),
    Skill(id=14, title='React', field_id=3),
    Skill(id=15, title='C/C++', field_id=3),
    Skill(id=16, title='Python', field_id=3),
    Skill(id=17, title='Database Management', field_id=3),
]

companies = [
    Company(id=1, email="contact@company1.com", name="Tech Innovators", job_ids=[1, 2, 4, 10]),
    Company(id=2, email="hr@company2.com", name="Israel Tours", job_ids=[3, 6, 8]),
    Company(id=3, email="info@company3.com", name="Product Masters", job_ids=[5, 7, 9])
]
